# Generated by Django 3.2.19 on 2023-06-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a05_admin', '0002_auto_20230620_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sex',
            field=models.IntegerField(choices=[(1, 'male'), (2, 'female')], default=1, verbose_name='sex'),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(help_text='older than 18', verbose_name='age'),
        ),
    ]
