# Generated by Django 2.2.28 on 2023-05-29 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='author_name')),
            ],
        ),
        migrations.CreateModel(
            name='wife',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='wife name')),
                ('husband', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='oto.Author')),
            ],
        ),
    ]
