# Generated by Django 2.2.28 on 2023-05-31 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20230531_0847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='uid',
            field=models.CharField(default='', max_length=20, verbose_name='related uid'),
        ),
        migrations.AddField(
            model_name='comment',
            name='uname',
            field=models.CharField(default='', max_length=30, verbose_name='related uname'),
        ),
        migrations.AddField(
            model_name='post',
            name='uid',
            field=models.CharField(default='', max_length=20, verbose_name='related uid'),
        ),
        migrations.AddField(
            model_name='post',
            name='uname',
            field=models.CharField(default='', max_length=30, verbose_name='related uname'),
        ),
    ]
