# Generated by Django 3.2.19 on 2023-06-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a06_admin_diy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='worker_name')),
                ('age', models.IntegerField(help_text='>18', verbose_name='worker_age')),
            ],
            options={
                'verbose_name': 'a06_worker',
                'verbose_name_plural': 'a06_worker',
                'db_table': 'a06_worker',
            },
        ),
    ]
