# Generated by Django 3.2.19 on 2023-06-08 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a02_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='question',
            table='demo_comment',
        ),
    ]
