# Generated by Django 3.2.19 on 2023-06-08 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a02_model', '0003_alter_question_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='car',
            table='a02_car',
        ),
        migrations.AlterModelTable(
            name='manufacture',
            table='a02_manufacture',
        ),
    ]
