# Generated by Django 3.2.19 on 2023-06-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a02_model', '0005_place_restaurant_waiter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('friends', models.ManyToManyField(related_name='_a02_model_student_friends_+', to='a02_model.Student')),
            ],
            options={
                'db_table': 'a02_student',
            },
        ),
    ]
