# Generated by Django 2.2.28 on 2023-05-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # CreateModel: 建一个表
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, verbose_name='name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='price')),
            ],
        ),
    ]
