"""
Django settings for django3 project.

Generated by 'django-admin startproject' using Django 3.2.19.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
#E:\Z_Frond_Back_workplace\07_Python\django_projects\02_Django3
BASE_DIR = Path(__file__).resolve().parent.parent



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 加密session 的。
SECRET_KEY = 'django-insecure-0!gn%$_gg$-j^@#)#l7e2^dh8(&5rnp6nwq*!ocxiy$bq7jj-%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["47.88.59.226", "127.0.0.1"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',  #自带的
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'a01_basic',
    'a02_model',
    'a03_view',
    "a04_template",
    "a05_admin",
    "a06_admin_diy"

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django3.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        #在 BASE_DIR/templates 里面没有找到的话， 那就在 app 里面的 templates 里面 找
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# 服务器部署时候的 一个配置
WSGI_APPLICATION = 'django3.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# DATABASES = {
#     # 表示默认数据库
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         # 目标 数据库的 名字
#         'NAME': 'dj_02_djando3_study',
#         'USER': 'root',
#         'PASSWORD': 'Woxhhxd990812?',
#         'HOST': '47.88.59.226',
#         'PORT': '3306'
#     }
# }

DATABASES = {
    # 表示默认数据库
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        # 目标 数据库的 名字
        'NAME': 'dj_database1_dj3_study',
        'USER': 'postgres',
        'PASSWORD': '',
        'HOST': '127.0.0.1',
        'PORT': '5432'
    }
}



# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Berlin'

USE_I18N = True

USE_L10N = True

# USE_TZ=True means timezone support is enabled, USE_TZ=False means timezone is not enabled.
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# static file(html/css)
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
)

# 100 mins session time.
SESSION_COOKIE_AGE = 6000000

# 指定登陆的 url， 和  @login_required 装饰器 有关， 假如 没有登陆， 会自动跳转到这个路径
LOGIN_URL = "/a03/login/"
