# Generated by Django 2.2.28 on 2023-05-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='username')),
                ('password', models.CharField(max_length=32, verbose_name='pwd')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='update time')),
            ],
        ),
    ]
