# Generated by Django 2.2.28 on 2023-05-30 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myNote_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='myNote_user',
        ),
    ]
