# Generated by Django 3.2.19 on 2023-06-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a03_view', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('password', models.CharField(max_length=8)),
                ('sex', models.CharField(max_length=5)),
                ('salary', models.FloatField()),
            ],
            options={
                'db_table': 'a03_person',
            },
        ),
    ]
